app_id: d7e27953-730e-4601-8132-82828ecd512e
app_secret: zFV7608=@lcjyowMLEBN1)(
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token